
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


import App from "./pages/App.tsx";
import Archive from "./pages/Archive.tsx";
import FamilySettings from "./pages/FamilySettings.tsx";
import ProfileSettings from "./pages/ProfileSettings.tsx";
import SetupProfile from "./pages/SetupProfile.tsx";
import TaskManagement from "./pages/TaskManagement.tsx";

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect /> },
	{ path: "/auth/*", element: <StackHandlerRoutes /> },
	{ path: "/", element: <UserGuard><App /></UserGuard> },
	{ path: "/archive", element: <UserGuard><Archive /></UserGuard> },
	{ path: "/family-settings", element: <UserGuard><FamilySettings /></UserGuard> },
	{ path: "/familysettings", element: <UserGuard><FamilySettings /></UserGuard> },
	{ path: "/profile-settings", element: <UserGuard><ProfileSettings /></UserGuard> },
	{ path: "/profilesettings", element: <UserGuard><ProfileSettings /></UserGuard> },
	{ path: "/setup-profile", element: <SetupProfile /> },
	{ path: "/setupprofile", element: <SetupProfile /> },
	{ path: "/task-management", element: <UserGuard><TaskManagement /></UserGuard> },
	{ path: "/taskmanagement", element: <UserGuard><TaskManagement /></UserGuard> },

];
