
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";


import { StackHandlerRoutes, LoginRedirect } from "app/auth";


const App = lazy(() => import("./pages/App.tsx"));
const Archive = lazy(() => import("./pages/Archive.tsx"));
const FamilySettings = lazy(() => import("./pages/FamilySettings.tsx"));
const ProfileSettings = lazy(() => import("./pages/ProfileSettings.tsx"));
const SetupProfile = lazy(() => import("./pages/SetupProfile.tsx"));
const TaskManagement = lazy(() => import("./pages/TaskManagement.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/auth/redirect", element: <LoginRedirect /> },
	{ path: "/auth/*", element: <StackHandlerRoutes /> },
	{ path: "/", element: <UserGuard><App /></UserGuard> },
	{ path: "/archive", element: <UserGuard><Archive /></UserGuard> },
	{ path: "/family-settings", element: <UserGuard><FamilySettings /></UserGuard> },
	{ path: "/familysettings", element: <UserGuard><FamilySettings /></UserGuard> },
	{ path: "/profile-settings", element: <UserGuard><ProfileSettings /></UserGuard> },
	{ path: "/profilesettings", element: <UserGuard><ProfileSettings /></UserGuard> },
	{ path: "/setup-profile", element: <SetupProfile /> },
	{ path: "/setupprofile", element: <SetupProfile /> },
	{ path: "/task-management", element: <UserGuard><TaskManagement /></UserGuard> },
	{ path: "/taskmanagement", element: <UserGuard><TaskManagement /></UserGuard> },

];
